server:
  port: 8080
  servlet:
    context-path: / #可以省略不写
spring:
  datasource: #数据库连接配置
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: sakura1993
    url: jdbc:mysql://localhost:3306/pethome?useUnicode=true&characterEncoding=utf8
mybatis:
  type-aliases-package: com.hoki.zj.org.domain,com.hoki.zj.permission.domain, com.hoki.zj.system.domain #配置别名
  mapper-locations: classpath:com/hoki/zj/org/mapper/*Mapper.xml, classpath:com/hoki/zj/permission/mapper/*Mapper.xml, classpath:com/hoki/zj/system/mapper/*Mapper.xml #扫描mapper映射文件,根据规范来写,可以省略不写
logging:
  level:
    com:
      hoki:
        zj: trace
    root: info
